# Development overrides
services:
  web:
    ports:
      - "${PORT:-8080}:80"

  livereload:
    image: node:alpine
    stop_grace_period: 1s
    working_dir: /app
    command: sh -c "npm install -g livereload && livereload /app/public --port 35729 --bind 0.0.0.0"
    volumes:
      - ../dist:/app/public
    networks:
      - internal
